apiVersion: batch/v1
kind: Job
metadata:
  generateName: py42-
  labels:
    job-group: sim-job
spec:
  completions: 96
  completionMode: Indexed
  parallelism: 24
  ttlSecondsAfterFinished: 100
  template:
    metadata:
      labels:
        job-group: sim-job
    spec:
      volumes:
      - name: pvc
        persistentVolumeClaim:
          claimName: py42-results
      containers:
      - name: run-script
        image: 192.168.237.101:32000/py42:24062502
        command: ["/bin/bash", "-c", "/home/user/py42/k8runner.sh"]
        reserources:
          requests:
            cpu: "1"
        volumeMounts:
          - name: pvc
            mountPath: /usr/share/py42/results
      restartPolicy: Never
  backoffLimit: 1 
  